---
- name: playbook Ubuntu Install
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - name: UTILS - get username
      shell: whoami
      register: username

  tasks:

    # ============================================
    # Criando o diretório $HOME/bin
    # ============================================
    - name: UBUNTU - Create $HOME/bin Directory
      file:
        path: "$HOME/bin"
        state: directory
        mode: 0700

    # ============================================
    # Removendo os diretório do #HOME que eu não uso
    # ============================================
    - name: UBUNTU - Remove useless folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "~/Templates"
        - "~/Public"
        - "~/examples.desktop"

    # ============================================
    # Criando o diretório de autostart
    # ============================================
    - name: UBUNTU - create autostart folder
      file:
       path: "$HOME/.config/autostart"
       state: directory

    # ============================================
    # instala ferramentas, dependencies e programas utils
    # ============================================
    - name: UBUNTU - Install packages and dependencies
      become: true
      become_method: sudo
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - git-extras
        - meld
        - jq
        - vim
        - gdebi-core
        - gnome-tweak-tool
        - python-pip
        - browser-plugin-vlc
        - lame
        - sound-juicer
        - imagemagick
        - ubuntu-restricted-extras
        - neofetch
        - terminator
        - apt-transport-https
        - software-properties-common
        - zip
        - gzip
        - unzip
        - bzip2
        - tar
        - nano
        - chrome-gnome-shell

    # ============================================
    # Instalando o Visual Studio Code
    # ============================================
    - import_tasks: vs_code_install.yaml

    # ============================================
    # Instalando o Spotify
    # ============================================
    - import_tasks: spotify_install.yaml

    # ===========================================
    # Instalando o Dropbox
    # ===========================================
    - include_tasks: dropbox/dropbox_install.yaml
      vars:
        user: "{{ username.stdout }}"

    # ============================================
    # Instalando o Albert
    # ============================================
    - include_tasks: albert_install.yaml

    # ===========================================
    # Instalando o Google Chrome
    # ===========================================
    - include_tasks: google_chrome_install.yaml

    # ============================================
    # Instalando os Themes
    # ============================================
    - import_tasks: gnome_custom_install.yaml
      vars:
        user: "{{ username.stdout }}"

    # ============================================
    # Disable all extension first
    # ============================================
    - name: EXTENSION - Disable all extension first
      shell: gsettings set org.gnome.shell enabled-extensions "[]"

    # ===========================================
    # Instalando a Extensão 'Hide Activities'
    # ===========================================
    - include_tasks: gnome_extensions.yaml
      vars:
        url: https://extensions.gnome.org/extension-data/hide-activities-button%40gnome-shell-extensions.bookmarkd.xyz.v1.shell-extension.zip
        filename: hide_activities_extension.zip
        user: "{{ username.stdout }}"

    # ===========================================
    # Instalando a Extensão 'Move Clock'
    # ===========================================
    - include_tasks: gnome_extensions.yaml
      vars:
        url: https://extensions.gnome.org/extension-data/Move_Clockrmy.pobox.com.v19.shell-extension.zip
        filename: clock_extension.zip
        home_folder: "{{ ansible_env.HOME }}"
        user: "{{ username.stdout }}"

    # ===========================================
    # Instalando a Extensão 'Open Weather'
    # ===========================================
    - include_tasks: gnome_extensions.yaml
      vars:
        url: https://extensions.gnome.org/extension-data/openweather-extension%40jenslody.de.v97.shell-extension.zip
        filename: open_weather.zip
        home_folder: "{{ ansible_env.HOME }}"
        user: "{{ username.stdout }}"

    # ===========================================
    # Clean Dependencies
    # ===========================================

    # pra consertar possíveis dependencias e pacotes quebrados
    - name: CLEAN - Fix broken packages
      become: true
      become_method: sudo
      shell: apt -f -y install

    # deletar os pacotes .deb em '/var/cache/apt/archives/'
    - name: CLEAN - Remove useless packages from the cache
      become: true
      become_method: sudo
      apt:
        autoclean: yes

    # remover pacotes não mais utilizados
    - name: CLEAN - Remove dependencies that are no longer required
      become: true
      become_method: sudo
      apt:
        autoremove: yes

    # ===========================================
    # Instalando os meus dotfiles
    # ===========================================
    - include_tasks: dotfiles.yaml
      vars:
        user: "{{ username.stdout }}"