---
- name: playbook Ubuntu Install
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:

    - name: UTILS - get username
      shell: whoami
      register: username

  tasks:

    # ============================================
    # Instalando o Libre Office
    # ============================================
    - import_tasks: libreoffice_install.yaml

    # ============================================
    # Instalando o Transmission
    # ============================================
    - import_tasks: transmission_install.yaml

    # ============================================
    # Instalando o Telegram Desktop
    # ============================================
    - include_tasks: telegram/telegram_install.yaml
      vars:
        telegram_folder: $HOME/bin/Telegram
        user: "{{ username.stdout }}"
