---
- name: ALBERT - add key
  become: yes
  apt_key:
    url: 'https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.04/Release.key'
    state: present

- name: ALBERT - Add repository
  become: true
  become_method: sudo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /
    state: present
    filename: albert

- name: ALBERT - install
  become: yes
  apt:
    name: albert
    state: present