# ============================================
# File that install and configure Atom
# ============================================
---
- name: ATOM - install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: ATOM - install apt key
  become: yes
  apt_key:
    url: 'https://packagecloud.io/AtomEditor/atom/gpgkey'
    state: present

- name: ATOM - add atom repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    filename: atom
    state: present

- name: ATOM - installing
  become: yes
  apt:
    name: atom
    state: present

- name: ATOM - install packages
  become: yes
  shell: >
    apm list --bare | grep -E '^{{ item }}@'
    && echo 'Already installed.'
    || apm install '{{ item }}'
  with_items:
    - 'file-icons'
    - atom-material-ui
    - atom-material-syntax-dark
    - atom-beautify
    - language-docker
    - language-conky
    - pigments
    - minimap
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"