# ============================================
# File that install Themes
# ============================================

---

# ============================================
# adicionando repositórios dos Themes
# ============================================
- name: THEMES - Add repositories
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item.key }}"
    filename: "{{ item.value }}"
  loop:
    - {key: 'ppa:tista/adapta',value: "adapta_theme"}
    - {key: 'ppa:papirus/papirus',value: "adapta_icon_theme"}

# ============================================
# Instalando os Themes
# ============================================
- name: THEMES - installing
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - adapta-gtk-theme
      - papirus-icon-theme

# ============================================
# Set theme to Adapta-Nokto
# ============================================
- name: THEME - set to Adapta
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Adapta-Nokto"

# ============================================
# Set icons-theme to Papirus-Dark
# ============================================
- name: THEME - set icons theme Adapta
  shell: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

# ============================================
# Set Dash position do BOTTOM
# ============================================
- name: THEME - change Dash position
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM

# ============================================
# Change Dash icon size to 20
# ============================================
- name: THEME - change dash icon size
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 20

# ============================================
# Disable Trash icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  shell: gsettings set org.gnome.nautilus.desktop trash-icon-visible false

# ============================================
# Disable Network Servers icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  shell: gsettings set org.gnome.nautilus.desktop network-icon-visible false

# ============================================
# Disable Home folder icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  shell: gsettings set org.gnome.nautilus.desktop home-icon-visible false

# ============================================
# Disable Mounted Volumes icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  shell: gsettings set org.gnome.nautilus.desktop volumes-visible false

# ============================================
# Change control buttons to the left position
# ============================================
- name: THEME - Change control buttons to the left
  shell: gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'

# ============================================
# Change 'show apps' button to the left
# ============================================
- name: THEME - Change 'show apps' button to the left
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true

# ============================================
# Copy the wallpaper to $HOME/Pictures
# ============================================
- name: THEME - Copy wallpaper file
  copy: 
    src: files/wallpaper.jpg
    dest: /home/{{ user }}/Pictures/wallpaper.jpg

# ============================================
# Set favorite-app in Dash
# ============================================
- name: THEME - Set Dash Icons
  shell: gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'terminator.desktop', 'spotify.desktop']"

# ============================================
# Set Wallpaper
# ============================================
- name: THEME - Set GNOME Wallpaper
  shell: gsettings set org.gnome.desktop.background picture-uri file:///home/{{ user }}/Pictures/wallpaper.jpg

# ============================================
# Set Wallpaper in lockscreen
# ============================================
- name: THEME - Set GNOME Wallpaper lockscreen
  shell: gsettings set org.gnome.desktop.screensaver picture-uri file:///home/{{ user }}/Pictures/wallpaper.jpg

  # ###################################
  # testando extensions

- name: EXTENSION - Apply Move Clock
  get_url:
    url: "{{ move_clock_extension_url }}"
    dest: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"

- name: EXTENSION - get uuid Move Clock
  shell: unzip -c "/home/{{ user }}/Downloads/{{ hide_activities_filename }}" metadata.json | grep uuid | cut -d \" -f4
  register: uuid_clock_extension

- name: EXTENSION - Create 'Move Clock' Extension Directory
  file:
    path: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid_clock_extension }}"
    state: directory
    mode: 0700

- name: EXTENSION - Extract extension in folder
  unarchive:
    src: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid_clock_extension }}"

- name: EXTENSION - Apply extension
  shell: gnome-shell-extension-tool -e {{ uuid_clock_extension }}

- name: EXTENSION - delete zip
  file:
    path: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"
    state: absent
