# ============================================
# File that install Themes
# ============================================

---

# ============================================
# adicionando repositórios dos Themes
# ============================================
- name: THEMES - Add repositories
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item.key }}"
    filename: "{{ item.value }}"
  loop:
    - {key: 'ppa:tista/adapta',value: "adapta_theme"}
    - {key: 'ppa:papirus/papirus',value: "adapta_icon_theme"}

# ============================================
# Instalando os Themes
# ============================================
- name: THEMES - installing
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - adapta-gtk-theme
      - papirus-icon-theme

- name: THEME - set to Adapta
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Adapta-Nokto"

- name: THEME - set icons theme Adapta
  shell: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

- name: THEME - change sibebar position
  shell: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM

- name: THEME - Copy wallpaper file
  copy: 
    src: files/wallpaper.jpg
    dest: /home/{{ user }}/Pictures/wallpaper.jpg

- name: THEME - Set GNOME Wallpaper
  become_user: "{{ user }}"
  shell: gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'terminator.desktop', 'spotify.desktop']"

# - name: Install python-psutil package
#   become: true
#   become_method: sudo
#   apt: 
#     name: python-psutil

- name: THEME - Set GNOME Wallpaper
  become_user: "{{ user }}"
  shell: gsettings set org.gnome.desktop.background picture-uri file:///home/{{ user }}/Pictures/wallpaper.jpg

- name: THEME - Set GNOME Wallpaper lockscreen
  become_user: "{{ user }}"
  shell: gsettings set org.gnome.desktop.screensaver picture-uri file:///home/{{ user }}/Pictures/wallpaper.jpg
    