# ============================================
# File that install Themes
# ============================================

---

# ============================================
# adicionando repositórios dos Themes
# ============================================
- name: THEMES - Add repositories
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item.key }}"
    filename: "{{ item.value }}"
  loop:
    - {key: 'ppa:tista/adapta',value: "adapta_theme"}
    - {key: 'ppa:papirus/papirus',value: "adapta_icon_theme"}

# ============================================
# Instalando os Themes
# ============================================
- name: THEMES - installing
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - adapta-gtk-theme
      - papirus-icon-theme

# ============================================
# Set theme to Adapta-Nokto
# ============================================
- name: THEME - set to Adapta
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "Adapta-Nokto"

# ============================================
# Set icons-theme to Papirus-Dark
# ============================================
- name: THEME - set icons theme Adapta
  gsettings:
    schema: org.gnome.desktop.interface
    key: icon-theme
    value: "Papirus-Dark"

# ============================================
# Set Dash position do BOTTOM
# ============================================
- name: THEME - change Dash position
  gsettings:
    schema: org.gnome.shell.extensions.dash-to-dock
    key: dock-position
    value: "BOTTOM"

# ============================================
# Change Dash icon size to 20
# ============================================
- name: THEME - change dash icon size
  gsettings:
    schema: org.gnome.shell.extensions.dash-to-dock
    key: dash-max-icon-size
    value: "20"

# ============================================
# Disable Trash icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  gsettings:
    schema: org.gnome.nautilus.desktop
    key: trash-icon-visible
    value: "false"

# ============================================
# Disable Network Servers icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  gsettings:
    schema: org.gnome.nautilus.desktop
    key: network-icon-visible
    value: "false"

# ============================================
# Disable Home folder icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  gsettings:
    schema: org.gnome.nautilus.desktop
    key: home-icon-visible
    value: "false"

# ============================================
# Disable Mounted Volumes icon on Desktop
# ============================================
- name: THEME - Disable Trash icon on Desktop
  gsettings:
    schema: org.gnome.nautilus.desktop
    key: volumes-visible
    value: "false"

# ============================================
# Change control buttons to the left position
# ============================================
- name: THEME - Change control buttons to the left
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: button-layout
    value: "close,minimize,maximize:"

# ============================================
# Change 'Show Apps' buttons to the left position
# ============================================
- name: THEME - Change 'Show Apps' buttons to the left position
  gsettings:
    schema: org.gnome.shell.extensions.dash-to-dock
    key: show-apps-at-top
    value: "true"

# ============================================
# Copy the wallpaper to $HOME/Pictures
# ============================================
- name: THEME - Copy wallpaper file
  copy: 
    src: files/wallpaper.jpg
    dest: /home/{{ user }}/Pictures/wallpaper.jpg

# ============================================
# Set favorite-app in Dash
# ============================================
- name: THEME - Set Dash Icons
  gsettings:
    schema: org.gnome.shell
    key: favorite-apps
    value: "['org.gnome.Nautilus.desktop', 'google-chrome.desktop', 'terminator.desktop', 'spotify.desktop']"

# ============================================
# Set Wallpaper
# ============================================
- name: THEME - Set GNOME Wallpaper
  gsettings:
    schema: org.gnome.desktop.background
    key: picture-uri
    value: "file:///home/{{ user }}/Pictures/wallpaper.jpg"

# ============================================
# Set Wallpaper in lockscreen
# ============================================
- name: THEME - Set GNOME Wallpaper lockscreen
  gsettings:
    schema: org.gnome.desktop.screensaver
    key: picture-uri
    value: "file:///home/{{ user }}/Pictures/wallpaper.jpg"
    