---
# ============================================
# Download 'Move Clock' extension
# ============================================
- name: EXTENSION - Download extension
  get_url:
    url: "{{ url }}"
    dest: "/home/{{ user }}/Downloads/{{ filename }}"

# ============================================
# get uuid Move Clock
# ============================================
- name: EXTENSION - get uuid
  shell: unzip -c "/home/{{ user }}/Downloads/{{ filename }}" metadata.json | grep uuid | cut -d \" -f4
  args:
    warn: false
  register: uuid

# ============================================
# Create 'Move Clock' Extension Directory
# ============================================
- name: EXTENSION - Create Extension Directory
  file:
    path: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid.stdout }}"
    state: directory
    mode: 0700
  changed_when: no

# ============================================
# Extract extension in folder
# ============================================
- name: EXTENSION - Extract extension in folder
  unarchive:
    src: "/home/{{ user }}/Downloads/{{ filename }}"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid.stdout }}"

# ============================================
# Apply extension
# ============================================
- name: EXTENSION - Apply extension
  shell: gnome-shell-extension-tool --enable-extension {{ uuid.stdout }}

# ============================================
# delete zip
# ============================================
- name: EXTENSION - delete zip
  file:
    path: "/home/{{ user }}/Downloads/{{ filename }}"
    state: absent
  changed_when: no