---
# ============================================
# Download 'Move Clock' extension
# ============================================
- name: EXTENSION - Download 'Move Clock' extension
  get_url:
    url: "{{ move_clock_extension_url }}"
    dest: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"

# ============================================
# get uuid Move Clock
# ============================================
- name: EXTENSION - get uuid Move Clock
  shell: unzip -c "/home/{{ user }}/Downloads/{{ hide_activities_filename }}" metadata.json | grep uuid | cut -d \" -f4
  register: uuid_clock_extension

# ============================================
# Create 'Move Clock' Extension Directory
# ============================================
- name: EXTENSION - Create 'Move Clock' Extension Directory
  file:
    path: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid_clock_extension.stdout }}"
    state: directory
    mode: 0700

# ============================================
# Extract extension in folder
# ============================================
- name: EXTENSION - Extract extension in folder
  unarchive:
    src: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/{{ uuid_clock_extension.stdout }}"

# ============================================
# Apply extension
# ============================================
- name: EXTENSION - Apply extension
  shell: gnome-shell-extension-tool -e {{ uuid_clock_extension.stdout }}

# ============================================
# delete zip
# ============================================
- name: EXTENSION - delete zip
  file:
    path: "/home/{{ user }}/Downloads/{{ hide_activities_filename }}"
    state: absent