---
- name: "GOOGLE CHROME - Download"
  get_url:
   url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
   dest: "."

- name: "GOOGLE CHROME - Installing"
  become: true
  become_method: sudo
  shell: gdebi google-chrome-stable_current_amd64.deb

- name: "GOOGLE CHROME - removing installer"
  file:
    path: "google-chrome-stable_current_amd64.deb"
    state: absent