# ============================================
# File that install Themes
# ============================================

---

# ============================================
# adicionando repositórios dos Themes
# ============================================
- name: THEMES - Add repositories
  become: true
  become_method: sudo
  apt_repository:
    repo: "{{ item.key }}"
    filename: "{{ item.value }}"
  loop:
    - {key: 'ppa:tista/adapta',value: "adapta_theme"}
    - {key: 'ppa:papirus/papirus',value: "adapta_icon_theme"}

# ============================================
# Instalando os Themes
# ============================================
- name: THEMES - installing
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - adapta-gtk-theme
      - papirus-icon-theme

- name: THEME - set to Adapta
  shell: gsettings set org.gnome.desktop.interface gtk-theme "Adapta-Nokto"

- name: THEME - set icons theme Adapta
  shell: gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
    